### ISSUE TITLE
Timeout issues during execution of `LaunchTcUnit.bat` on VM

### ISSUE THREAD

**Issue by vegarosthus** [tcunit/TcUnit-Runner#30]
Has anyone experienced issues with the `LaunchTcUnit.bat` script timing out during execution? I execute the script on an Azure VM running Windows 10, through Azure Pipelines, and my console output _occasionally_  end up looking like this. 

![image](https://user-images.githubusercontent.com/18138493/139810714-974c00b3-7ba2-4864-86ef-2a360ef5112c.png)

The VM is running 4 cores with 7 GB RAM, so I don't think this is a performance related issue, allthough I feel that some actions,  like closing the Remote Desktop connection to the VM, or restarting the VM, seem to mitigate the issue. 

One issue that might be a symptom of some underlying issue, is that the TcXaeShell application doesn't seem to be properly shut down after the script executes (and ends abruptedly?). 

![image](https://user-images.githubusercontent.com/18138493/139811172-23727fda-fc8b-4d5a-b27a-c099543a99c7.png)

I'm attaching my azure-pipelines.yml file as well, as I'm unsure what is causing this behavior. Keep in mind that this occurs only some times, so it is kind of hard to reproduce and stabilize the error. 

```
# Demo CI workflow with TcUnit-Runner
name: TcUnit-Runner  
 
trigger:
- main
pr:
- main
 
pool: 
    name: AC4Build   
    demands:
    - agent.name -equals TcUnitTests # self-hosted agent  

 
steps: 
 
- checkout: self
  displayName: Checkout repository  
 
- task: CmdLine@2
  displayName: Run PLC unit-tests with TcUnit-Runner 
  condition: succeeded()
  inputs:
    failOnStderr: true
    # Start TcUnit-Runner with a timeout of 3 min
    script: '"C:\Program Files (x86)\TcUnit-Runner\LaunchTcUnit.bat" -U 3 -t PlcTask -w 3.1.4024.20'
     
- task: PublishTestResults@2
  displayName: Publish TcUnit results
  condition: or(succeeded(),failed())     
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: '**/TcUnit_xUnit_results.xml'
```

Any help would be appreciated.

**Comment by sagatowski** [comment]
Hi @vegarosthus! 
Have you tried calling the TcUnit-Runner directly in your pipeline (skipping the bat-file)?
Does the zombie-process exist after the time-out (code 17), or is it created after some other sequence?

**Comment by vegarosthus** [comment]
Hi @sagatowski! Thanks for the quick reply. I tried executing the application directly by changing my .yml-file to this

```
# Demo CI workflow with TcUnit-Runner
name: TcUnit-Runner  
 
trigger:
- main
pr:
- main
 
pool: 
    name: AC4Build   
    demands:
    - agent.name -equals TcUnitTests # self-hosted agent  

 
steps: 
 
- checkout: self
  displayName: Checkout repository  
 
- task: CmdLine@2
  displayName: Run PLC unit-tests with TcUnit-Runner 
  condition: succeeded()
  inputs:
    failOnStderr: true
    # Start TcUnit-Runner with a timeout of 3 min
    #script: '"C:\Program Files (x86)\TcUnit-Runner\LaunchTcUnit.bat" -U 3 -t PlcTask -w 3.1.4024.20'
    script: '"C:\Program Files (x86)\TcUnit-Runner\TcUnit-Runner.exe" --VisualStudioSolutionFilePath="C:\agent\_work\3\s\TcUnit-Runner Demo.sln" --Timeout="3" --TcUnitTaskName="PlcTask" --TcVersion="3.1.4024.20"'
     
- task: PublishTestResults@2
  displayName: Publish TcUnit results
  condition: or(succeeded(),failed())     
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: '**/TcUnit_xUnit_results.xml'
```

but this results in a Access denied-error

![image](https://user-images.githubusercontent.com/18138493/139836060-a9787c0c-bb8a-4ef7-9a91-fa492d0ff4eb.png)

Does the script do anything special in regards to giving the application the correct permissions?

I'm not sure what you mean by the second question, but the TcXaeShell Application process is created by the script (or technically TcUnitRunner i guess) and are not being quit if that ends abruptly. That remains the case also if TcUnitRunner is called directly by the pipeline.
